### ISSUE TITLE
Feature list different from MoveCraft?

### ISSUE THREAD

**Issue by TomLewis** [StarQuestMinecraft/StarQuestPrivate#3]
Hey guys
Owner of PirateCraft here.
Long time movecraft fan, been using it for 3+ years, I got notified by a staff member that StarQuest shut down and opened up all your custom plugins & movecraft to the public! This is amazing! 
Im not much of a developer, but this really interests me to find out the features you have added over time for Movecraft, is there a list of additional features? Also what version of Spigot does this work upto? 
Have you considered merging your changes to the main Movecraft repo?

Thank you for opening up your code, this is fascinating coming from a server owner that uses nothing but public plugins.
- Tom (GodsDead/Frozenbeard)

**Comment by StarQuestMinecraft** [comment]
Hey there, this is Dibujaron.

Unfortunately even we don't know what's different from stock movecraft. We forked from standard movecraft in 2013 and haven't re-merged since. Certain features that we have are also in stock movecraft but are implemented differently such as our versions of autopilot and cannons. Our movecraft is very custom tailored for SQ and probably will not work for you without the assistance of a developer to change it around for you. Here is a list of features that I know that we added off the top of my head:
- cross-bungee-server and cross-world ship jumping (this is the #1 feature we added )
- autopilot (not cruise control, works a bit differently)
- shift as movement instead of right-click
- starship style cannons
- parked ship protection with worldguard (called ship shields)
- ship owner protection so that only certain people can fly the ship (useful for spawn parking etc)
- "cryo pods" as a ship-compatible respawning system (another parallel feature with the stock version's bed system)
- ship torpedoes
- extensible boarding ramps
- "ground vehicles" with hovercraft and cars
- Stained glass as a block that is permeable to ships but solid to players (for hangar doors)
- Jamming devices that block the use of autopilot
- a simple event-based API for use by other plugins.

And there is probably more that I forgot about. However because SQMovecraft was specialized for SQ, we did streamline it by removing some features that we had no use for, including the ability for ships to go in water, which I think you probably need.
